#!/usr/bin/env bash
# Prepare the 1000G CEPH trio (NA12878 + parents NA12891/NA12892) test inputs
# for nf-cavalier, restricted to chr22 to keep file sizes manageable.
#
# Outputs:
#   <OUTDIR>/{NA12878,NA12891,NA12892}.<REGION>.bam[.bai]
#   <OUTDIR>/trio.<REGION>.short.vcf.gz[.csi]
#   <OUTDIR>/trio.<REGION>.struc.vcf.gz[.csi]
#   <script dir>/alignments.tsv
#   <script dir>/test_ceph_trio.config   (use with: nextflow run . -c <this>)
#
# Requires: samtools, bcftools, curl (all >= recent htslib).
# Reference FASTA (pass -r) must be the GATK GRCh38 build; used to decode the
# upstream CRAMs during slicing.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTDIR="${SCRIPT_DIR}/data"
REF_FASTA=""
REGION="chr22"
THREADS=2

usage() {
    cat >&2 <<EOF
Usage: $0 -r REF_FASTA [-o OUTDIR] [-R REGION] [-t THREADS]

  -r REF_FASTA  GRCh38 reference FASTA (required; CRAM decode)
  -o OUTDIR     output directory (default: <script dir>/data)
  -R REGION     region to slice (default: chr22)
  -t THREADS    threads for samtools/bcftools (default: 4)
EOF
    exit 1
}

while getopts ":o:r:R:t:h" opt; do
    case $opt in
        o) OUTDIR="$OPTARG" ;;
        r) REF_FASTA="$OPTARG" ;;
        R) REGION="$OPTARG" ;;
        t) THREADS="$OPTARG" ;;
        h|*) usage ;;
    esac
done

[[ -z "$REF_FASTA" ]] && { echo "ERROR: -r REF_FASTA is required" >&2; usage; }
[[ -f "$REF_FASTA" ]] || { echo "ERROR: REF_FASTA not found: $REF_FASTA" >&2; exit 1; }

for cmd in samtools bcftools curl; do
    command -v "$cmd" >/dev/null || { echo "ERROR: $cmd not found in PATH" >&2; exit 1; }
done

mkdir -p "$OUTDIR"
cd "$OUTDIR"

SAMPLES=(NA12878 NA12891 NA12892)
PLATINUM_BASE="ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/illumina_platinum_pedigree/data/CEU"
CRAM_SUFFIX="alt_bwamem_GRCh38DH.20150706.CEU.illumina_platinum_ped.cram"

echo "[1/3] Slicing $REGION from Illumina Platinum Pedigree CRAMs to BAM"
for s in "${SAMPLES[@]}"; do
    out="${s}.${REGION}.bam"
    if [[ -s "$out" && -s "${out}.bai" ]]; then
        echo "  - $out (exists, skipping)"
        continue
    fi
    url="${PLATINUM_BASE}/${s}/alignment/${s}.${CRAM_SUFFIX}"
    echo "  - $s: $url"
    samtools view \
        --threads "$THREADS" \
        -T "$REF_FASTA" \
        -b -o "$out" \
        "$url" "$REGION"
    samtools index -@ "$THREADS" "$out"
done

VCF_URL="http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20220422_3202_phased_SNV_INDEL_SV/1kGP_high_coverage_Illumina.${REGION}.filtered.SNV_INDEL_SV_phased_panel.vcf.gz"

short_vcf="trio.${REGION}.short.vcf.gz"
struc_vcf="trio.${REGION}.struc.vcf.gz"

if [[ -s "$short_vcf" && -s "${short_vcf}.csi" && -s "$struc_vcf" && -s "${struc_vcf}.csi" ]]; then
    echo "[2/3] VCFs already present, skipping subset/split"
else
    echo "[2/3] Subsetting joint-called VCF to trio samples (dropping non-alt sites)"
    # Pipe: -s subsets samples first, then --min-ac on the second view sees only
    # the trio so AC is recomputed against the 3-sample subset.
    trio_vcf="trio.${REGION}.vcf.gz"
    bcftools view --threads "$THREADS" -s "$(IFS=,; echo "${SAMPLES[*]}")" -Ou "$VCF_URL" \
        | bcftools view --threads "$THREADS" --min-ac 1 -O z -o "$trio_vcf"
    bcftools index --threads "$THREADS" "$trio_vcf"

    echo "[3/3] Splitting into short (SNV/INDEL) and structural VCFs"
    # Records without an SVTYPE INFO tag are SNVs/indels; with SVTYPE are SVs.
    bcftools view --threads "$THREADS" -e 'INFO/SVTYPE!="."' -O z -o "$short_vcf" "$trio_vcf"
    bcftools index --threads "$THREADS" "$short_vcf"

    bcftools view --threads "$THREADS" -i 'INFO/SVTYPE!="."' -O z -o "$struc_vcf" "$trio_vcf"
    bcftools index --threads "$THREADS" "$struc_vcf"

    rm -f "$trio_vcf" "${trio_vcf}.csi"
fi

align_tsv="${SCRIPT_DIR}/alignments.tsv"
ped="${SCRIPT_DIR}/family.ped"
config="${SCRIPT_DIR}/test_ceph_trio.config"

echo "[+] Writing alignments.tsv -> $align_tsv"
{
    for s in "${SAMPLES[@]}"; do
        printf '%s\t%s\n' "$s" "${OUTDIR}/${s}.${REGION}.bam"
    done
} > "$align_tsv"

echo "[+] Writing config -> $config"
cat > "$config" <<EOF
// Generated by tests/ceph_trio/download.sh for REGION=${REGION}
// Usage: nextflow run . -c tests/ceph_trio/test_ceph_trio.config [-profile bahlolab]

params {
    alignments     = '${align_tsv}'
    ped            = '${ped}'
    short_vcf      = '${OUTDIR}/${short_vcf}'
    struc_vcf      = '${OUTDIR}/${struc_vcf}'
    lists          = 'HGNC:protein-coding,PAA:137,PAA:126'
    short_n_shards = 10
    struc_n_shards = 2
    // 1000G phased panel has only phased GT in FORMAT — no GQ/DP.
    short_format   = ['GT']
    // sceVCF needs AD/DP and qc_sce_chr — the 1000G phased panel has only
    // phased GT and the slice is region-limited, so skip it.
    qc_sce_vcf     = false
    // lower stringency for demo — these are healthy reference samples
    FILTER_SHORT_POP_DOM_MAX_AF  = 0.1
    FILTER_SHORT_POP_REC_MAX_AF  = 0.1
    FILTER_SHORT_POP_DOM_MAX_HOM = null
    FILTER_SHORT_POP_REC_MAX_HOM = null
    FILTER_SHORT_POP_DOM_MAX_AC  = null
    FILTER_SHORT_POP_REC_MAX_AC  = null
    FILTER_SHORT_CLINVAR_DISC_PAT = null
    FILTER_STRUC_POP_DOM_MAX_AF  = 0.1
    FILTER_STRUC_POP_REC_MAX_AF  = 0.1
    FILTER_STRUC_POP_DOM_MAX_HOM = null
    FILTER_STRUC_POP_REC_MAX_HOM = null
}
EOF

echo
echo "Done. Outputs in ${OUTDIR}:"
ls -lh "$short_vcf"* "$struc_vcf"* *."${REGION}".bam*
echo
echo "Generated:"
ls -lh "$align_tsv" "$config"
