
def validate_setup_params() {
    if (!params.config_out) {
        error "[setup_anno] --config_out is required (path for the generated nextflow.config)."
    }
    def cfg = file(params.config_out)
    if (cfg.exists()) {
        error "[setup_anno] --config_out '${cfg}' already exists; refusing to overwrite. Pick a different path."
    }
    if (!params.skip_revel && !params.url_revel) {
        log.warn "[setup_anno] url_revel is null (PLACEHOLDER); REVEL will be skipped. Set --url_revel or --skip_revel to silence."
    }
}

// Build the [url, out_name] download list for the GATK ref FASTA bundle.
def fasta_downloads(String base_url) {
    return [
        [ "${base_url}/Homo_sapiens_assembly38.fasta",     'Homo_sapiens_assembly38.fasta'     ],
        [ "${base_url}/Homo_sapiens_assembly38.fasta.fai", 'Homo_sapiens_assembly38.fasta.fai' ],
        [ "${base_url}/Homo_sapiens_assembly38.dict",      'Homo_sapiens_assembly38.dict'      ],
    ]
}

// Resolve absolute path (following symlinks back to storeDir).
def abs(p) { p ? file(p.toString()).toRealPath().toString() : null }

// Map asset name -> bool (params.skip_<asset>). Used to differentiate "skipped" from "no URL configured".
def asset_is_skipped(name) {
    def v = params["skip_${name}"]
    return v == null ? false : v
}

// Write the generated nextflow.config given a list of [asset_name, primary_path] tuples.
def write_generated_config(resolved) {
    def asset_to_param = [
        ref_fasta:     'ref_fasta',
        vep_cache:     'vep_cache',
        alphamissense: 'vep_alphamissense',
        revel:         'vep_revel',
        utr_annotator: 'vep_utr_annotator',
        gnomad:        'vcfanno_gnomad',
        cadd_snv:      'vcfanno_cadd_snv',
        cadd_indel:    'vcfanno_cadd_indel',
        clinvar:       'vcfanno_clinvar',
        svafotate:     'svafdb',
        ref_gene:      'ref_gene',
        somalier:      'somalier_dir',
    ]
    def resolved_map = resolved.collectEntries { name, p -> [(name): p] }
    def out = file(params.config_out)
    if (out.exists()) {
        error "[setup_anno] config_out '${out}' already exists; refusing to overwrite."
    }

    def lines = []
    lines << "// Generated by nf-cavalier/setup_anno on ${new Date().format('yyyy-MM-dd HH:mm:ss')}"
    lines << ''
    lines << 'params {'
    lines << "    vep_cache_ver = '${params.vep_cache_ver}'"
    lines << ''

    asset_to_param.each { asset, param ->
        if (resolved_map.containsKey(asset)) {
            lines << "    ${param} = '${resolved_map[asset]}'"
        } else if (asset_is_skipped(asset)) {
            lines << "    // ${param} = '...'  // skipped via --skip_${asset}; set manually if needed"
        } else {
            lines << "    // ${param} = '...'  // not configured (e.g. PLACEHOLDER URL); set manually if needed"
        }
    }

    lines << ''
    lines << '    // SpliceAI scores must be downloaded manually — see VEP plugin docs for instructions:'
    lines << '    //   https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html#spliceai'
    lines << '    // Download spliceai_scores.raw.snv.hg38.vcf.gz and spliceai_scores.raw.indel.hg38.vcf.gz,'
    lines << '    // then generate .tbi indices with: tabix -p vcf <file.vcf.gz>'
    lines << "    // vep_spliceai_snv   = '...'"
    lines << "    // vep_spliceai_indel = '...'"
    lines << '}'
    lines << ''

    out.parent?.mkdirs()
    out.text = lines.join('\n')
    log.info "[setup_anno] Wrote ${out}"
}
